name: "My Code Review Pal"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  code_review:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - uses: gardais/wemake-python-styleguide@master
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
