name: "My Code Review Pal"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  code_review:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          path: src
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
